8 feature8 myflightslist
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k5-cb-reactive11 pull request #15
Opened 2022-09-06 23:48 UTC by AmarilloVel

# Description
 Created a component to render the flight items using flatlist component from react native.
modified the component flightitem, adding props as:
*  originLong
*  originShort
*  destLong
*  destShort
*  date
*  passengers
  
  ## Screenshots 

![image](https://user-images.githubusercontent.com/56924427/188759184-adcfd6ce-8f07-4ca9-a843-e36203b8c06d.png)

2022-09-06 23:50 UTC, TonyHdez-Pi approved these changes

2022-09-07 21:18 UTC, wiltrouble requested changes

2022-09-07 21:18 UTC, wiltrouble commented on flight-reservation/components/FlightListComponent/index.js
> +const data = [
Remove this data in a separate file

2022-09-07 21:54 UTC, Astroyayo commented on flight-reservation/components/FlightListComponent/index.js
> +const data = [
changes addressed

2022-09-07 22:01 UTC, wiltrouble requested changes

2022-09-07 22:01 UTC, wiltrouble commented on flight-reservation/components/FlightListComponent/index.js
> +    <View style={styles.itemContainer}>
Remove this View

2022-09-07 22:06 UTC, Astroyayo commented on flight-reservation/components/FlightListComponent/index.js
> +    <View style={styles.itemContainer}>
addresed

2022-09-07 22:10 UTC, wiltrouble approved these changes
Looks good 👌

2022-09-07 22:19 UTC, featlast approved these changes
well done Nice Code !!!!

2022-09-07 22:22 UTC, merged