44 feature44 userauthenticationfunctionality
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k5-cb-reactive11 pull request #45
Opened 2022-10-01 14:48 UTC by Astroyayo

# Description
Users can now signup or log in using their email and password
  
  ## Screenshots 
NA

2022-10-01 14:50 UTC, AmarilloVel approved these changes
well done

2022-10-03 23:42 UTC, YilKanda requested changes

2022-10-03 23:42 UTC, YilKanda commented on flightReservationCLI/src/hooks/emailPwd.js
> +    console.log(email, password);
Don't leave debug code on GitHub.

2022-10-03 23:42 UTC, YilKanda commented on flightReservationCLI/src/hooks/emailPwd.js
> +    console.log(email, password);
Don't leave debug code on GitHub.

2022-10-04 00:37 UTC, merged